model:
  name: lpsrgan
  args:
    num_blocks: 3
    dropout_prob: 0.5

optimizer_g:
  name: adam
  args:
    lr: 2.e-4
    betas: [0.9, 0.999]

optimizer_d:
  name: adam
  args:
    lr: 1.e-4
    betas: [0.5, 0.999]

func_train: lpsrgan_pretrain
func_val: lpsrgan_val
training_stage: pretrain
tag_view: paired_pretrain
visualize_interval: 0

train_dataset:
  dataset:
    name: ufpr_paired
    args:
      roots:
        - ./ufpr-sr/UFPR-SR-plates/1920_1080
        - ./ufpr-sr/UFPR-SR-plates/1280_0960
      phase: training
  wrapper:
    name: lpsrgan
    args:
      imgW: 48
      imgH: 16
      aug: True
      image_aspect_ratio: 3
      background: (127, 127, 127)
      rectify: False
  batch: 16

val_dataset:
  dataset:
    name: ufpr_paired
    args:
      roots:
        - ./ufpr-sr/UFPR-SR-plates/1920_1080
        - ./ufpr-sr/UFPR-SR-plates/1280_0960
      phase: validation
  wrapper:
    name: lpsrgan
    args:
      imgW: 48
      imgH: 16
      aug: False
      image_aspect_ratio: 3
      background: (127, 127, 127)
      rectify: False
  batch: 16

loss:
  name: lpsrganLoss
  args:
    pixel_weight: 1.0
    perceptual_weight: 0.1
    adversarial_weight: 0.0
    use_perceptual: True
    use_ocr: False
    ocr_weight: 0.0
    load: null

early_stopper:
  patience: 50
  min_delta: 0
  counter: 0

reduce_on_plateau:
  mode: min
  factor: 0.5
  patience: 10
  min_lr: 1.e-7
  verbose: True

epoch_max: 100
epoch_save: 25
resume: null
