model:
  name: gplpr_trainable_ocr
  args:
    alphabet: "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ"
    nc: 3
    imgW: 96
    imgH: 32
    K: 7
    isSeqModel: True
    head: 2
    inner: 256
    isl2Norm: True
    load: null

optimizer_g:
  name: adam
  args:
    lr: 1.e-4
    betas: [0.9, 0.999]

func_train: ocr_train
func_val: ocr_val
training_stage: ocr
ocr_input_key: hr

train_dataset:
  dataset:
    name: ufpr_paired
    args:
      roots:
        - ./ufpr-sr/UFPR-SR-plates/1920_1080
        - ./ufpr-sr/UFPR-SR-plates/1280_0960
      phase: training
  wrapper:
    name: lpsrgan
    args:
      imgW: 48
      imgH: 16
      aug: True
      image_aspect_ratio: 3
      background: (127, 127, 127)
      rectify: False
  batch: 16

val_dataset:
  dataset:
    name: ufpr_paired
    args:
      roots:
        - ./ufpr-sr/UFPR-SR-plates/1920_1080
        - ./ufpr-sr/UFPR-SR-plates/1280_0960
      phase: validation
  wrapper:
    name: lpsrgan
    args:
      imgW: 48
      imgH: 16
      aug: False
      image_aspect_ratio: 3
      background: (127, 127, 127)
      rectify: False
  batch: 16

loss:
  name: noopLoss
  args: {}

early_stopper:
  patience: 30
  min_delta: 0
  counter: 0

reduce_on_plateau:
  mode: min
  factor: 0.5
  patience: 5
  min_lr: 1.e-7
  verbose: True

epoch_max: 100
epoch_save: 25
resume: null
